#!/bin/bash
# Test the Food Consumption System

echo "=== Food Consumption System Test ==="
echo "Testing the new food consumption modal feature..."
echo ""
echo "1. Start the game server:"
echo "   cd /home/shaun/repos/cosmic-explorer"
echo "   ./test_server.sh"
echo ""
echo "2. Open browser to http://localhost:5000"
echo ""
echo "3. Start a new game"
echo ""
echo "4. Test the food system:"
echo "   - Click on the food icon (🍞) in the top HUD"
echo "   - The food modal should open"
echo "   - Try consuming different amounts of food"
echo "   - Observe health restoration and animations"
echo ""
echo "5. Test edge cases:"
echo "   - Try consuming when health is full (should be disabled)"
echo "   - Try consuming more food than available (should be disabled)"
echo "   - Consume food to restore health after taking damage"
echo ""
echo "Expected behaviors:"
echo "- Food icon shows hover effect and tooltip"
echo "- Modal displays current health and food supply"
echo "- Consumption options show actual health gain"
echo "- Health bar animates when food is consumed"
echo "- Success sound plays on consumption"
echo "- Modal updates immediately after consumption"